SLURM_JOBID=6041984
SLURM_JOB_NODELIST=jagupard35
SLURM_NNODES=1
SLURMTMPDIR=
working directory = /sailhome/fongsu/superhf
[2023-04-24 21:45:07,669] [WARNING] [runner.py:190:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1: setting --include=localhost:0,1
[2023-04-24 21:45:07,688] [INFO] [runner.py:540:main] cmd = /sailhome/fongsu/rm/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None src/reward_modelling/reward_model.py --model_name_or_path=EleutherAI/gpt-neo-1.3B --output_dir=/nlp/scr/fongsu/reward_model_HH/train_first_half/ --logging_steps=100 --per_device_train_batch_size=4 --per_device_eval_batch_size=4 --gradient_accumulation_steps=4 --num_train_epochs=1 --do_eval=False --evaluation_strategy=steps --eval_steps=100 --save_total_limit=5 --save_strategy=steps --save_steps=1000 --learning_rate=1e-5 --weight_decay=0.001 --report_to=wandb --gradient_checkpointing=True --ddp_find_unused_parameters=False --deepspeed src/reward_modelling/ds_configs/base_configs.json
[2023-04-24 21:45:12,674] [INFO] [launch.py:222:main] 0 NCCL_P2P_DISABLE=1
[2023-04-24 21:45:12,674] [INFO] [launch.py:229:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-04-24 21:45:12,674] [INFO] [launch.py:235:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-04-24 21:45:12,674] [INFO] [launch.py:246:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-04-24 21:45:12,674] [INFO] [launch.py:247:main] dist_world_size=2
[2023-04-24 21:45:12,674] [INFO] [launch.py:249:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-04-24 21:45:17,454] [INFO] [comm.py:586:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
04/24/2023 21:54:58 - WARNING - datasets.load - Using the latest cached version of the module from /nlp/scr/fongsu/.cache/modules/datasets_modules/datasets/openai--webgpt_comparisons/8b5d5879cdc98c4c0099af6053dffe8d504588d43d3b11f1b1ec223ab1e8db0a (last modified on Fri Apr 21 00:08:24 2023) since it couldn't be found locally at openai/webgpt_comparisons., or remotely on the Hugging Face Hub.
04/24/2023 21:54:58 - WARNING - datasets.builder - Found cached dataset webgpt_comparisons (/nlp/scr/fongsu/.cache/openai___webgpt_comparisons/default/0.0.0/8b5d5879cdc98c4c0099af6053dffe8d504588d43d3b11f1b1ec223ab1e8db0a)
04/24/2023 22:05:27 - WARNING - datasets.builder - Found cached dataset webgpt_comparisons (/nlp/scr/fongsu/.cache/openai___webgpt_comparisons/default/0.0.0/8b5d5879cdc98c4c0099af6053dffe8d504588d43d3b11f1b1ec223ab1e8db0a)
04/24/2023 22:05:36 - WARNING - datasets.builder - Using custom data configuration Anthropic--hh-rlhf-c8cd8dc58ab67414
04/24/2023 22:05:36 - WARNING - datasets.builder - Found cached dataset json (/nlp/scr/fongsu/.cache/Anthropic___json/Anthropic--hh-rlhf-c8cd8dc58ab67414/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
[2023-04-24 22:05:36,978] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 882344
[2023-04-24 22:05:37,330] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 882345
[2023-04-24 22:05:37,331] [ERROR] [launch.py:434:sigkill_handler] ['/sailhome/fongsu/rm/bin/python', '-u', 'src/reward_modelling/reward_model.py', '--local_rank=1', '--model_name_or_path=EleutherAI/gpt-neo-1.3B', '--output_dir=/nlp/scr/fongsu/reward_model_HH/train_first_half/', '--logging_steps=100', '--per_device_train_batch_size=4', '--per_device_eval_batch_size=4', '--gradient_accumulation_steps=4', '--num_train_epochs=1', '--do_eval=False', '--evaluation_strategy=steps', '--eval_steps=100', '--save_total_limit=5', '--save_strategy=steps', '--save_steps=1000', '--learning_rate=1e-5', '--weight_decay=0.001', '--report_to=wandb', '--gradient_checkpointing=True', '--ddp_find_unused_parameters=False', '--deepspeed', 'src/reward_modelling/ds_configs/base_configs.json'] exits with return code = 1
